# Question 1

***Create a numpy array starting from 2 till 50 with a stepsize of 3.***

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(2,50,3)
print(arr1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

***Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.***

In [12]:
def listing(x,i):
    a = int(input('Enter number '+ str(i+1)+' for array '+str(x)+' : '))
    return a
print('List 1\n')
l1 = [listing(1,i) for i in range(0,5)]
print('\nList 2\n')
l2 = [listing(2,i) for i in range(0,5)]
arr2 = np.array(l1)
arr3 = np.array(l2)
print('\nNumpy Array 1 - ',arr2)
print('\nNumpy Array 2 - ',arr3)

List 1

Enter number 1 for array 1 : 23
Enter number 2 for array 1 : 34
Enter number 3 for array 1 : 32
Enter number 4 for array 1 : 14
Enter number 5 for array 1 : 45

List 2

Enter number 1 for array 2 : 7
Enter number 2 for array 2 : 45
Enter number 3 for array 2 : 23
Enter number 4 for array 2 : 78
Enter number 5 for array 2 : 96

Numpy Array 1 -  [23 34 32 14 45]

Numpy Array 2 -  [ 7 45 23 78 96]


In [15]:
#Concatenated Array
print('\nConcatenated Array: ', np.concatenate((arr2,arr3)))

#Sorted arrays
print('Sorted Arrays:') 
print('Numpy array 1: ',np.sort(arr2))
print('Numpy array 2: ',np.sort(arr3))


Concatenated Array:  [23 34 32 14 45  7 45 23 78 96]
Sorted Arrays:
Numpy array 1:  [14 23 32 34 45]
Numpy array 2:  [ 7 23 45 78 96]


# Question 3

***Write a code snippet to find the dimensions of a ndarray and its size.***

In [27]:
arr4 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print('Dimension of the given array is ',arr4.ndim)
print('Size of the given array is ',arr4.size)

Dimension of the given array is  2
Dimension of the given array is  9


# Question 4

***How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims***

In [30]:
# The Process of converting a 1D Numpy Array to a 2D Numpy Array can be done using RESHAPE function

# Let's suppose an 1D array 'arr5' of 10 Elements
arr5 = np.arange(10)
print('1D Array - ',arr5)

# For converting this 1D array to 2D array, lets apply reshape function with arguments (2,5)
arr6 = arr5.reshape((2,5))
print('2D Array reshaped from 1D array - ',arr6)

# Note the product of reshaping arguments should result to the initial array size it is converted from
# Here - Product of (2,5) results to (10)

# Also this can be achieved by 'newaxis' and 'expand_dims' 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Question 5

***Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()***

In [58]:
# Consider arr7 and arr8 to be two square numpy arrays

arr7 = np.zeros((3,3))
arr8 = np.ones((3,3))

print('The Square matrices are\n',arr7,'\n\n',arr8)

print('\nVertically Stacked Array : \n\n',np.vstack((arr7,arr8)))
print('\nHorizontally Stacked Array : \n\n',np.hstack((arr7,arr8)))

The Square matrices are
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Vertically Stacked Array : 

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Horizontally Stacked Array : 

 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


# Question 6

***How to get unique items and counts of unique items?***

In [65]:
arr9 = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr9)
unique_items, unique_count = np.unique(arr9,return_counts=True)
print('\nUnique_items - ',unique_items)
print('Unique_count - ',unique_count)

[[1 2 3]
 [3 4 5]
 [5 6 7]]

Unique_items -  [1 2 3 4 5 6 7]
Unique_count -  [1 1 2 1 2 1 1]
